/**
 * Mapa estático de nombres de rutas, ciudades y áreas de Pokémon
 * traducidas al español.
 *
 * PokeAPI no proporciona nombres en español para las localizaciones — solo
 * en/de/fr —, así que este diccionario es la única fuente de verdad.
 *
 * Las entradas sin traducción conocida se mostrarán en inglés con el nombre
 * capitalizado (fallback definido en `getLocationNameEs`).
 *
 * Para añadir más traducciones, solo hay que añadir entradas aquí:
 *   "nombre-pokeapi": "Nombre en español"
 */

const LOCATION_ES: Record<string, string> = {
  // ── KANTO ──
  "pallet-town": "Pueblo Paleta",
  "viridian-city": "Ciudad Verde",
  "pewter-city": "Ciudad Plateada",
  "cerulean-city": "Ciudad Celeste",
  "vermilion-city": "Ciudad Carmín",
  "lavender-town": "Pueblo Lavanda",
  "celadon-city": "Ciudad Azafrán",
  "saffron-city": "Ciudad Azulona",
  "fuchsia-city": "Ciudad Fucsia",
  "cinnabar-island": "Isla Canela",
  "viridian-forest": "Bosque Verde",
  "digletts-cave": "Cueva Diglett",
  "mt-moon": "Monte Moon",
  "rock-tunnel": "Túnel Roca",
  "power-plant": "Central Eléctrica",
  "safari-zone": "Zona Safari",
  "pokemon-mansion": "Mansión Pokémon",
  "pokemon-tower": "Torre Pokémon",
  "silph-co": "Silph S.A.",
  "seafoam-islands": "Islas Espuma",
  "victory-road": "Calle Victoria",
  "indigo-plateau": "Meseta Añil",
  "cerulean-cave": "Cueva Celeste",
  "route-1": "Ruta 1",
  "route-2": "Ruta 2",
  "route-3": "Ruta 3",
  "route-4": "Ruta 4",
  "route-5": "Ruta 5",
  "route-6": "Ruta 6",
  "route-7": "Ruta 7",
  "route-8": "Ruta 8",
  "route-9": "Ruta 9",
  "route-10": "Ruta 10",
  "route-11": "Ruta 11",
  "route-12": "Ruta 12",
  "route-13": "Ruta 13",
  "route-14": "Ruta 14",
  "route-15": "Ruta 15",
  "route-16": "Ruta 16",
  "route-17": "Ruta 17",
  "route-18": "Ruta 18",
  "route-19": "Ruta 19",
  "route-20": "Ruta 20",
  "route-21": "Ruta 21",
  "route-22": "Ruta 22",
  "route-23": "Ruta 23",
  "route-24": "Ruta 24",
  "route-25": "Ruta 25",

  // ── JOHTO ──
  "new-bark-town": "Pueblo Primavera",
  "cherrygrove-city": "Ciudad Cerezo",
  "violet-city": "Ciudad Malva",
  "azalea-town": "Pueblo Azalea",
  "goldenrod-city": "Ciudad Trigal",
  "ecruteak-city": "Ciudad Iris",
  "olivine-city": "Cierta Olivo",
  "cianwood-city": "Ciudad Orquídea",
  "mahogany-town": "Pueblo Caoba",
  "blackthorn-city": "Ciudad Endrino",
  "lake-of-rage": "Lago de la Ira",
  "mt-mortar": "Monte Mortero",
  "ice-path": "Sendero Helado",
  "dark-cave": "Cueva Oscura",
  "union-cave": "Cueva Unión",
  "slowpoke-well": "Pozo Slowpoke",
  "ruins-of-alph": "Ruinas Alfa",
  "national-park": "Parque Nacional",
  "bell-tower": "Torre Campana",
  "whirl-islands": "Islas Remolino",
  "mt-silver": "Monte Plateado",
  "route-29": "Ruta 29",
  "route-30": "Ruta 30",
  "route-31": "Ruta 31",
  "route-32": "Ruta 32",
  "route-33": "Ruta 33",
  "route-34": "Ruta 34",
  "route-35": "Ruta 35",
  "route-36": "Ruta 36",
  "route-37": "Ruta 37",
  "route-38": "Ruta 38",
  "route-39": "Ruta 39",
  "route-40": "Ruta 40",
  "route-41": "Ruta 41",
  "route-42": "Ruta 42",
  "route-43": "Ruta 43",
  "route-44": "Ruta 44",
  "route-45": "Ruta 45",
  "route-46": "Ruta 46",
  "route-47": "Ruta 47",
  "route-48": "Ruta 48",

  // ── HOENN ──
  "littleroot-town": "Pueblo Hoja",
  "oldale-town": "Pueblo Roble",
  "petalburg-city": "Ciudad Petalia",
  "rustboro-city": "Ciudad Férrica",
  "dewford-town": "Pueblo Calagra",
  "slateport-city": "Ciudad Portual",
  "mauville-city": "Ciudad Malvalona",
  "verdanturf-town": "Pueblo Verdantur",
  "fallarbor-town": "Pueblo Oromar",
  "fortree-city": "Ciudad Arborada",
  "lilycove-city": "Ciudad Liquidácea",
  "mossdeep-city": "Ciudad Puntatopo",
  "sootopolis-city": "Ciudad Almarina",
  "ever-grande-city": "Ciudad Colosalia",
  "petalburg-woods": "Bosque Petalia",
  "rusturf-tunnel": "Túnel Férrico",
  "granite-cave": "Cueva Granito",
  "new-mauville": "Nueva Malvalona",
  "fiery-path": "Senda Ignea",
  "mt-chimney": "Monte Chimenea",
  "jagged-pass": "Paso Irregular",
  "weather-institute": "Instituto Meteorológico",
  "safari-zone-hoenn": "Zona Safari (Hoenn)",
  "mt-pyramid": "Monte Pirámide",
  "magma-hideout": "Escondite Magma",
  "aqua-hideout": "Escondite Aqua",
  "sky-pillar": "Pilar Celeste",
  "victory-road-hoenn": "Calle Victoria (Hoenn)",
  "route-101": "Ruta 101",
  "route-102": "Ruta 102",
  "route-103": "Ruta 103",
  "route-104": "Ruta 104",
  "route-105": "Ruta 105",
  "route-106": "Ruta 106",
  "route-107": "Ruta 107",
  "route-108": "Ruta 108",
  "route-109": "Ruta 109",
  "route-110": "Ruta 110",
  "route-111": "Ruta 111",
  "route-112": "Ruta 112",
  "route-113": "Ruta 113",
  "route-114": "Ruta 114",
  "route-115": "Ruta 115",
  "route-116": "Ruta 116",
  "route-117": "Ruta 117",
  "route-118": "Ruta 118",
  "route-119": "Ruta 119",
  "route-120": "Ruta 120",
  "route-121": "Ruta 121",
  "route-122": "Ruta 122",
  "route-123": "Ruta 123",
  "route-124": "Ruta 124",
  "route-125": "Ruta 125",
  "route-126": "Ruta 126",
  "route-127": "Ruta 127",
  "route-128": "Ruta 128",
  "route-129": "Ruta 129",
  "route-130": "Ruta 130",
  "route-131": "Ruta 131",
  "route-132": "Ruta 132",
  "route-133": "Ruta 133",
  "route-134": "Ruta 134",

  // ── SINNOH ──
  "twinleaf-town": "Pueblo Hoja",
  "sandgem-town": "Pueblo Arena",
  "jubilife-city": "Ciudad Jubileo",
  "oreburgh-city": "Cierta Pirita",
  "floaroma-town": "Pueblo Floral",
  "eterna-city": "Ciudad Vetusta",
  "hearthome-city": "Ciudad Corazón",
  "solaceon-town": "Pueblo Sosiego",
  "veilstone-city": "Cierta Rocavelo",
  "pastoria-city": "Ciudad Pastiza",
  "celestic-town": "Pueblo Celestino",
  "canalave-city": "Ciudad Canal",
  "snowpoint-city": "Ciudad Puntaneva",
  "sunyshore-city": "Ciudad Marina",
  "pokemon-league-sinnoh": "Liga Pokémon (Sinnoh)",
  "oreburgh-mine": "Mina Pirita",
  "eterna-forest": "Bosque Vetusta",
  "mt-cornet": "Monte Corona",
  "great-marsh": "Gran Pantano",
  "iron-island": "Isla Férrea",
  "valor-lakefront": "Lago Valor",
  "acuity-lakefront": "Lago Agudeza",
  "verity-lakefront": "Lago Veraz",
  "distortion-world": "Mundo Distorsión",
  "spear-pillar": "Pilar Saeta",
  "route-201": "Ruta 201",
  "route-202": "Ruta 202",
  "route-203": "Ruta 203",
  "route-204": "Ruta 204",
  "route-205": "Ruta 205",
  "route-206": "Ruta 206",
  "route-207": "Ruta 207",
  "route-208": "Ruta 208",
  "route-209": "Ruta 209",
  "route-210": "Ruta 210",
  "route-211": "Ruta 211",
  "route-212": "Ruta 212",
  "route-213": "Ruta 213",
  "route-214": "Ruta 214",
  "route-215": "Ruta 215",
  "route-216": "Ruta 216",
  "route-217": "Ruta 217",
  "route-218": "Ruta 218",
  "route-219": "Ruta 219",
  "route-220": "Ruta 220",
  "route-221": "Ruta 221",
  "route-222": "Ruta 222",
  "route-223": "Ruta 223",
  "route-224": "Ruta 224",
  "route-225": "Ruta 225",
  "route-226": "Ruta 226",
  "route-227": "Ruta 227",
  "route-228": "Ruta 228",
  "route-229": "Ruta 229",
  "route-230": "Ruta 230",

  // ── UNOVA ──
  "nuvema-town": "Pueblo Césped",
  "accumula-town": "Pueblo Acumula",
  "striaton-city": "Cierta Esmalte",
  "nacrene-city": "Ciudad Caolín",
  "castelia-city": "Ciudad Porcelana",
  "nimbasa-city": "Ciudad Mayólica",
  "driftveil-city": "Ciudad Loza",
  "mistralton-city": "Ciudad Loza",
  "icirrus-city": "Ciudad Hielo",
  "opelucid-city": "Ciudad Teja",
  "humilau-city": "Ciudad Humilau",
  "lacunosa-town": "Pueblo Lacunosa",
  "undella-town": "Pueblo Undella",
  "virbank-city": "Ciudad Bahía",
  "aspertia-city": "Ciudad Asperia",
  "floccesy-town": "Pueblo Floccesy",
  "virbank-complex": "Complejo Bahía",
  "pinwheel-forest": "Bosque Giratorio",
  "desert-resort": "Resort Desierto",
  "relic-castle": "Castillo Relicario",
  "cold-storage": "Cámara Frigorífica",
  "dragonspiral-tower": "Torre Espiral",
  "celestial-tower": "Torre Celeste",
  "wellspring-cave": "Cueva Manantial",
  "mistralton-cave": "Cueva Loza",
  "chargestone-cave": "Cueva Pontezuela",
  "twist-mountain": "Monte Retorcido",
  "giant-chasm": "Gran Abismo",
  "abyssal-ruins": "Ruinas Abisales",
  championship: "Campeonato",
  "white-forest": "Bosque Blanco",
  "black-city": "Ciudad Negra",
  "route-1-unova": "Ruta 1 (Unova)",
  "route-2-unova": "Ruta 2 (Unova)",
  "route-3-unova": "Ruta 3 (Unova)",
  "route-4-unova": "Ruta 4 (Unova)",
  "route-5-unova": "Ruta 5 (Unova)",
  "route-6-unova": "Ruta 6 (Unova)",
  "route-7-unova": "Ruta 7 (Unova)",
  "route-8-unova": "Ruta 8 (Unova)",
  "route-9-unova": "Ruta 9 (Unova)",
  "route-10-unova": "Ruta 10 (Unova)",
  "route-11-unova": "Ruta 11 (Unova)",
  "route-12-unova": "Ruta 12 (Unova)",
  "route-13-unova": "Ruta 13 (Unova)",

  // ── KALOS (Gen 6) — placeholders. Traduce la parte derecha. ──
  "vaniville-town": "vaniville-town",
  "vaniville-pathway": "vaniville-pathway",
  "aquacorde-town": "aquacorde-town",
  "santalune-city": "santalune-city",
  "santalune-forest": "santalune-forest",
  "lumiose-city": "lumiose-city",
  "prism-tower": "prism-tower",
  "lysandre-labs": "lysandre-labs",
  "camphrier-town": "camphrier-town",
  "shabboneau-castle": "shabboneau-castle",
  "parfum-palace": "parfum-palace",
  "cyllage-city": "cyllage-city",
  "ambrette-town": "ambrette-town",
  "ambrette-aquarium": "ambrette-aquarium",
  "geosenge-town": "geosenge-town",
  "shalour-city": "shalour-city",
  "tower-of-mastery": "tower-of-mastery",
  "reflection-cave": "reflection-cave",
  "coumarine-city": "coumarine-city",
  "laverre-city": "laverre-city",
  "dendemille-town": "dendemille-town",
  "anistar-city": "anistar-city",
  "couriway-town": "couriway-town",
  "snowbelle-city": "snowbelle-city",
  "kiloude-city": "kiloude-city",
  "battle-maison": "battle-maison",
  "kalos-route-1": "kalos-route-1",
  "kalos-route-2": "kalos-route-2",
  "kalos-route-3": "kalos-route-3",
  "kalos-route-4": "kalos-route-4",
  "kalos-route-5": "kalos-route-5",
  "kalos-route-6": "kalos-route-6",
  "kalos-route-7": "kalos-route-7",
  "kalos-route-8": "kalos-route-8",
  "kalos-route-9": "kalos-route-9",
  "kalos-route-10": "kalos-route-10",
  "kalos-route-11": "kalos-route-11",
  "kalos-route-12": "kalos-route-12",
  "kalos-route-13": "kalos-route-13",
  "kalos-route-14": "kalos-route-14",
  "kalos-route-15": "kalos-route-15",
  "kalos-route-16": "kalos-route-16",
  "kalos-route-17": "kalos-route-17",
  "kalos-route-18": "kalos-route-18",
  "kalos-route-19": "kalos-route-19",
  "kalos-route-20": "kalos-route-20",
  "kalos-route-21": "kalos-route-21",
  "kalos-route-22": "kalos-route-22",
  "kalos-victory-road": "kalos-victory-road",
  "kalos-pokemon-league": "kalos-pokemon-league",
  "avance-trail": "avance-trail",
  "ouvert-way": "ouvert-way",
  "parterre-way": "parterre-way",
  "versant-road": "versant-road",
  "palais-lane": "palais-lane",
  "riviere-walk": "riviere-walk",
  "muraille-coast": "muraille-coast",
  "spikes-passage": "spikes-passage",
  "menhir-trail": "menhir-trail",
  "miroir-way": "miroir-way",
  "fourrage-road": "fourrage-road",
  "lumiose-badlands": "lumiose-badlands",
  "laverre-nature-trail": "laverre-nature-trail",
  "poke-ball-factory": "poke-ball-factory",
  "brun-way": "brun-way",
  "melancolie-path": "melancolie-path",
  "frost-cavern": "frost-cavern",
  "mamoswine-road": "mamoswine-road",
  "vallee-etroite-way": "vallee-etroite-way",
  "grande-vallee-way": "grande-vallee-way",
  "winding-woods": "winding-woods",
  "pokemon-village": "pokemon-village",
  "derniere-way": "derniere-way",
  "detourner-way": "detourner-way",
  "azure-bay": "azure-bay",
  "glittering-cave": "glittering-cave",
  "connecting-cave": "connecting-cave",
  "zubat-roost": "zubat-roost",
  "kalos-power-plant": "kalos-power-plant",
  "team-flare-secret-hq": "team-flare-secret-hq",
  "terminus-cave": "terminus-cave",
  "lost-hotel": "lost-hotel",
  "chamber-of-emptiness": "chamber-of-emptiness",
  "sea-spirits-den": "sea-spirits-den",
  "battle-chateau": "battle-chateau",
  "friend-safari": "friend-safari",
  "unknown-dungeon": "unknown-dungeon",
  "blazing-chamber": "blazing-chamber",
  "flood-chamber": "flood-chamber",
  "ironworks-chamber": "ironworks-chamber",
  "dragonmark-chamber": "dragonmark-chamber",
  "radiant-chamber": "radiant-chamber",
  "lumiose-station": "lumiose-station",
  "kiloude-station": "kiloude-station",

  // ── ALOLA (Gen 7) — placeholders. Traduce la parte derecha. ──
  "alola-route-1": "alola-route-1",
  "alola-route-2": "alola-route-2",
  "alola-route-3": "alola-route-3",
  "alola-route-4": "alola-route-4",
  "alola-route-5": "alola-route-5",
  "alola-route-6": "alola-route-6",
  "alola-route-7": "alola-route-7",
  "alola-route-8": "alola-route-8",
  "alola-route-9": "alola-route-9",
  "alola-route-10": "alola-route-10",
  "alola-route-11": "alola-route-11",
  "alola-route-12": "alola-route-12",
  "alola-route-13": "alola-route-13",
  "alola-route-14": "alola-route-14",
  "alola-route-15": "alola-route-15",
  "alola-route-16": "alola-route-16",
  "alola-route-17": "alola-route-17",
  "alola-route-1--hauoli-outskirts": "alola-route-1--hauoli-outskirts",
  "hauoli-city": "hauoli-city",
  "hauoli-city--beachfront": "hauoli-city--beachfront",
  "hauoli-city--shopping-district": "hauoli-city--shopping-district",
  "hauoli-city--marina": "hauoli-city--marina",
  "iki-town": "iki-town",
  "mahalo-trail": "mahalo-trail",
  "ruins-of-conflict": "ruins-of-conflict",
  "ten-carat-hill": "ten-carat-hill",
  "hauoli-cemetery": "hauoli-cemetery",
  "melemele-meadow": "melemele-meadow",
  "seaward-cave": "seaward-cave",
  "berry-fields": "berry-fields",
  "verdant-cavern": "verdant-cavern",
  "kalae-bay": "kalae-bay",
  "melemele-sea": "melemele-sea",
  "hano-grand-resort": "hano-grand-resort",
  "hano-beach": "hano-beach",
  "akala-meadow": "akala-meadow",
  "paniola-town": "paniola-town",
  "paniola-ranch": "paniola-ranch",
  "heahea-city": "heahea-city",
  "konikoni-city": "konikoni-city",
  "royal-avenue": "royal-avenue",
  "memorial-hill": "memorial-hill",
  "wela-volcano-park": "wela-volcano-park",
  "brooklet-hill": "brooklet-hill",
  "lush-jungle": "lush-jungle",
  "ruins-of-life": "ruins-of-life",
  "akala-outskirts": "akala-outskirts",
  "digletts-tunnel": "digletts-tunnel",
  "battle-royal-dome": "battle-royal-dome",
  "secluded-shore": "secluded-shore",
  "tapu-village": "tapu-village",
  "haina-desert": "haina-desert",
  "ulaula-meadow": "ulaula-meadow",
  "po-town": "po-town",
  "malie-city-proper": "malie-city-proper",
  "malie-garden": "malie-garden",
  "mount-hokulani": "mount-hokulani",
  "blush-mountain": "blush-mountain",
  "ruins-of-abundance": "ruins-of-abundance",
  "lake-of-the-sunne": "lake-of-the-sunne",
  "lake-of-the-moone": "lake-of-the-moone",
  "mount-lanakila": "mount-lanakila",
  "shady-house": "shady-house",
  "thrifty-megamart--abandoned-site": "thrifty-megamart--abandoned-site",
  "hokulani-observatory": "hokulani-observatory",
  "alola-pokemon-league": "alola-pokemon-league",
  "poni-meadow": "poni-meadow",
  "poni-wilds": "poni-wilds",
  "ancient-poni-path": "ancient-poni-path",
  "poni-breaker-coast": "poni-breaker-coast",
  "poni-grove": "poni-grove",
  "poni-plains": "poni-plains",
  "poni-coast": "poni-coast",
  "poni-gauntlet": "poni-gauntlet",
  "seafolk-village": "seafolk-village",
  "vast-poni-canyon": "vast-poni-canyon",
  "altar-of-the-sunne": "altar-of-the-sunne",
  "altar-of-the-moone": "altar-of-the-moone",
  "ruins-of-hope": "ruins-of-hope",
  "resolution-cave": "resolution-cave",
  "exeggutor-island": "exeggutor-island",
  "battle-tree": "battle-tree",
  "aether-paradise": "aether-paradise",
  "ultra-space": "ultra-space",

  // ── GALAR (Gen 8) — placeholders. Traduce la parte derecha. ──
  "galar-route-1": "galar-route-1",
  "galar-route-2": "galar-route-2",
  "galar-route-3": "galar-route-3",
  "galar-route-4": "galar-route-4",
  "galar-route-5": "galar-route-5",
  "galar-route-6": "galar-route-6",
  "galar-route-7": "galar-route-7",
  "galar-route-8": "galar-route-8",
  "galar-route-9": "galar-route-9",
  "galar-route-10": "galar-route-10",
  postwick: "postwick",
  wedgehurst: "wedgehurst",
  motostoke: "motostoke",
  "motostoke-outskirts": "motostoke-outskirts",
  "motostoke-riverbank": "motostoke-riverbank",
  turffield: "turffield",
  hulbury: "hulbury",
  hammerlocke: "hammerlocke",
  "hammerlocke-hills": "hammerlocke-hills",
  "stow-on-side": "stow-on-side",
  ballonlea: "ballonlea",
  circhester: "circhester",
  spikemuth: "spikemuth",
  "galar-pokemon-league": "galar-pokemon-league",
  "slumbering-weald": "slumbering-weald",
  "galar-mine": "galar-mine",
  "galar-mine-no-2": "galar-mine-no-2",
  "glimwood-tangle": "glimwood-tangle",
  "galar-iceberg-ruins": "galar-iceberg-ruins",
  "galar-iron-ruins": "galar-iron-ruins",
  "galar-rock-peak-ruins": "galar-rock-peak-ruins",
  "wild-area": "wild-area",
  "rolling-fields": "rolling-fields",
  "dappled-grove": "dappled-grove",
  "watchtower-ruins": "watchtower-ruins",
  "east-lake-axewell": "east-lake-axewell",
  "west-lake-axewell": "west-lake-axewell",
  "axews-eye": "axews-eye",
  "south-lake-miloch": "south-lake-miloch",
  "north-lake-miloch": "north-lake-miloch",
  "bridge-field": "bridge-field",
  "dusty-bowl": "dusty-bowl",
  "giants-mirror": "giants-mirror",
  "stony-wilderness": "stony-wilderness",
  "lake-of-outrage": "lake-of-outrage",
  "giants-seat": "giants-seat",
  "giants-foot": "giants-foot",
  "giants-bed": "giants-bed",
  "courageous-cavern": "courageous-cavern",
  "challenge-road": "challenge-road",
  "challenge-beach": "challenge-beach",
  "brawlers-cave": "brawlers-cave",
  "steamdrift-way": "steamdrift-way",
  "soothing-wetlands": "soothing-wetlands",
  "slippery-slope": "slippery-slope",
  "frostpoint-field": "frostpoint-field",
  "snowslide-slope": "snowslide-slope",
  "tunnel-to-the-top": "tunnel-to-the-top",
  "path-to-the-peak": "path-to-the-peak",
  "warm-up-tunnel": "warm-up-tunnel",
  "training-lowlands": "training-lowlands",
  "split-decision-ruins": "split-decision-ruins",
  "three-point-pass": "three-point-pass",
  "old-cemetery": "old-cemetery",
  "lakeside-cave": "lakeside-cave",
  "stepping-stone-sea": "stepping-stone-sea",
  "insular-sea": "insular-sea",
  "honeycalm-sea": "honeycalm-sea",
  "honeycalm-island": "honeycalm-island",
  "frigid-sea": "frigid-sea",
  "potbottom-desert": "potbottom-desert",
  "fields-of-honor": "fields-of-honor",
  "loamy-highlands": "loamy-highlands",
  "dyna-tree-hill": "dyna-tree-hill",
  "forest-of-focus": "forest-of-focus",
  "master-dojo": "master-dojo",
  "crown-shrine": "crown-shrine",
  "ballimere-lake": "ballimere-lake",
  freezington: "freezington",
  "max-lair": "max-lair",
  "roaring-sea-caves": "roaring-sea-caves",
  "galar-battle-tower": "galar-battle-tower",
  "tower-of-darkness": "tower-of-darkness",
  "tower-of-waters": "tower-of-waters",
  "loop-lagoon": "loop-lagoon",

  // ── HISUI (Legends: Arceus) — placeholders ──
  "jubilife-village": "jubilife-village",
  "obsidian-fieldlands": "obsidian-fieldlands",
  "crimson-mirelands": "crimson-mirelands",
  "cobalt-coastlands": "cobalt-coastlands",
  "coronet-highlands": "coronet-highlands",
  "alabaster-icelands": "alabaster-icelands",
  "sandgem-flats": "sandgem-flats",
  "lake-verity": "lake-verity",
  "floaro-gardens": "floaro-gardens",
  "aspiration-hill": "aspiration-hill",
  "nature-park": "nature-park",
  "raging-springs": "raging-springs",
  "goldlow-forest": "goldlow-forest",
  "diamond-settlement": "diamond-settlement",
  "mossy-cradle": "mossy-cradle",
  "solaceon-meadows": "solaceon-meadows",
  "kobold-lagoon": "kobold-lagoon",
  "spring-path": "spring-path",
  "hulking-grove": "hulking-grove",
  "ice-column-chamber": "ice-column-chamber",
  "rocky-stronghold": "rocky-stronghold",
  "temple-of-sinnoh": "temple-of-sinnoh",

  // ── PALDEA (Gen 9) — placeholders. Traduce la parte derecha. ──
  "cabo-poco": "Cabo Poco",
  "los-platos": "Los Platos",
  mesagoza: "Mesagoza",
  cortondo: "Cortondo",
  alfornada: "Alfornada",
  artazon: "Artazon",
  levincia: "Levincia",
  zapapico: "Zapapico",
  cascarrafa: "Cascarrafa",
  "porto-marinada": "Porto Marinada",
  medali: "Medali",
  montenevera: "Montenevera",
  "pokemon-league": "Pokemon League",
  "naranja-academy": "Naranja Academy",
  "paldea-south-province-area-one": "Paldea South Province Area One",
  "paldea-south-province-area-two": "Paldea South Province Area Two",
  "paldea-south-province-area-three": "Paldea South Province Area Three",
  "paldea-south-province-area-four": "Paldea South Province Area Four",
  "paldea-south-province-area-five": "Paldea South Province Area Five",
  "paldea-south-province-area-six": "Paldea South Province Area Six",
  "paldea-east-province-area-one": "Paldea East Province Area One",
  "paldea-east-province-area-two": "Paldea East Province Area Two",
  "paldea-east-province-area-three": "Paldea East Province Area Three",
  "paldea-west-province-area-one": "Paldea West Province Area One",
  "paldea-west-province-area-two": "Paldea West Province Area Two",
  "paldea-west-province-area-three": "Paldea West Province Area Three",
  "paldea-north-province-area-one": "Paldea North Province Area One",
  "paldea-north-province-area-two": "Paldea North Province Area Two",
  "paldea-north-province-area-three": "Paldea North Province Area Three",
  "south-paldean-sea": "South Paldean Sea",
  "west-paldean-sea": "West Paldean Sea",
  "east-paldean-sea": "East Paldean Sea",
  "north-paldean-sea": "North Paldean Sea",
  "poco-path": "Poco Path",
  "inlet-grotto": "Inlet Grotto",
  "alfornada-cavern": "Alfornada Cavern",
  "grasswither-shrine": "Grasswither Shrine",
  "icerend-shrine": "Icerend Shrine",
  "groundblight-shrine": "Groundblight Shrine",
  "firescourge-shrine": "Firescourge Shrine",
  "tagtree-thicket": "Tagtree Thicket",
  "asado-desert": "Asado Desert",
  "casseroya-lake": "Casseroya Lake",
  "dalizapa-passage": "Dalizapa Passage",
  "glaseado-mountain": "Glaseado Mountain",
  "socarrat-trail": "Socarrat Trail",
  "area-zero": "Area Zero",
  "zero-lab": "Zero Lab",
  "schedar-squads-base": "Schedar Squad's Base",
  "navi-squads-base": "Navi Squad's Base",
  "segin-squads-base": "Segin Squad's Base",
  "ruchbah-squads-base": "Ruchbah Squad's Base",
  "caph-squads-base": "Caph Squad's Base",

  // ── SEVII ISLANDS (Kanto post-game) — placeholders ──
  "one-island": "One Island",
  "two-island": "Two Island",
  "three-island": "Three Island",
  "three-isle-path": "Three Isle Path",
  "six-island": "Six Island",
  "seven-island": "Seven Island",
  "birth-island": "Birth Island",
  "navel-rock": "Navel Rock",
  "faraway-island": "Faraway Island",
  "terra-cave": "Terra Cave",
  "marine-cave": "Marine Cave",
  "mirage-spot-island": "Mirage Spot (Island)",
  "mirage-spot-forest": "Mirage Spot (Forest)",
  "mirage-spot-cave": "Mirage Spot (Cave)",
  "mirage-spot-mountain": "Mirage Spot (Mountain)",
  "southern-island": "Southern Island",
  "sealed-chamber": "Sealed Chamber",
  "scorched-slab": "Scorched Slab",
  "island-cave": "Island Cave",
  "desert-ruins": "Desert Ruins",
  "ancient-tomb": "Ancient Tomb",
  "trackless-forest": "Trackless Forest",
  "pathless-plain": "Pathless Plain",
  "nameless-cavern": "Nameless Cavern",
  "fabled-cave": "Fabled Cave",
  "gnarled-den": "Gnarled Den",
  "crescent-isle": "Crescent Isle",
  "secret-islet": "Secret Islet",
  "secret-shore": "Secret Shore",
  "secret-meadow": "Secret Meadow",
  "soaring-in-the-sky": "Soaring in the Sky",
};

const AREA_SUFFIXES = [
  "-area",
  "-main",
  "-water",
  "-cave",
  "-entrance",
  "-exit",
  "-1f",
  "-2f",
  "-3f",
  "-b1f",
  "-b2f",
  "-b3f",
  "-b4f",
  "-roof",
  "-exterior",
  "-interior",
  "-back",
  "-front",
  "-south",
  "-north",
  "-east",
  "-west",
  "-center",
  "-outside",
  "-underground",
  "-depths",
  "-peak",
  "-bonus",
  "-special",
  "-championship",
  "-room",
  "-deep",
  "-shore",
  "-sea",
  "-path",
  "-tunnel",
  "-overworld",
  "-inside",
];

function extractBaseLocationName(name: string): {
  base: string;
  suffix: string | null;
} {
  for (const suffix of AREA_SUFFIXES) {
    if (name.endsWith(suffix)) {
      const base = name.slice(0, -suffix.length);
      return { base, suffix };
    }
  }
  return { base: name, suffix: null };
}

/**
 * Traduce un nombre de localización (location_area.name) al español.
 *
 * El algoritmo:
 * 1. Quita sufijos de zona (-area, -main, -water, etc.)
 * 2. Busca el nombre base en `LOCATION_ES`
 * 3. Si encuentra: devuelve la traducción + sufijo limplio opcional
 * 4. Si no: capitaliza y devuelve el nombre crudo en inglés
 *
 * @param name Nombre interno de PokeAPI (ej. "pallet-town-area")
 * @returns Nombre localizado (ej. "Pueblo Paleta")
 */
export function getLocationNameEs(name: string): string {
  const { base, suffix } = extractBaseLocationName(name);
  const translated = LOCATION_ES[base] ?? null;

  if (translated) {
    return suffix ? `${translated} (${cleanSuffix(suffix)})` : translated;
  }

  // Fallback: capitalizar el nombre en inglés
  const fallback = name
    .split("-")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
  return fallback;
}

function cleanSuffix(suffix: string): string {
  const map: Record<string, string> = {
    "-area": "área",
    "-main": "principal",
    "-water": "agua",
    "-cave": "cueva",
    "-entrance": "entrada",
    "-exit": "salida",
    "-1f": "1F",
    "-2f": "2F",
    "-3f": "3F",
    "-b1f": "S1",
    "-b2f": "S2",
    "-b3f": "S3",
    "-b4f": "S4",
    "-roof": "azotea",
    "-exterior": "exterior",
    "-interior": "interior",
    "-back": "trasera",
    "-front": "frontal",
    "-south": "sur",
    "-north": "norte",
    "-east": "este",
    "-west": "oeste",
    "-center": "centro",
    "-outside": "exterior",
    "-underground": "subterráneo",
    "-depths": "profundidades",
    "-peak": "cima",
    "-bonus": "extra",
    "-special": "especial",
    "-room": "sala",
    "-deep": "fondo",
    "-shore": "orilla",
    "-sea": "mar",
    "-path": "sendero",
    "-tunnel": "túnel",
    "-overworld": "exterior",
    "-inside": "interior",
    "-championship": "campeonato",
  };
  return map[suffix] ?? suffix.replace(/^-/, "").replace(/-/g, " ");
}

/**
 * Instrucciones para traducir rutas manualmente:
 *
 * 1. Abre este archivo: `lib/location-names.ts`
 * 2. Busca la sección de la región que te interesa (KANTO, JOHTO, etc.)
 *    o añade una nueva sección con el nombre de la región en comentario.
 * 3. Añade una entrada con el formato:
 *      "nombre-pokeapi": "Nombre en español",
 *    Ejemplo:
 *      "lumiose-city": "Ciudad Luminalia",
 * 4. Guarda el archivo.
 * 5. Opcional: ejecuta `pnpm typecheck` para verificar que no hay errores.
 * 6. Refresca la página para ver los cambios en la app.
 *
 * Para encontrar el nombre PokeAPI, inspecciona la tabla de encuentros
 * de un Pokémon de la región que quieras traducir: verás el nombre inglés
 * en la columna "Ruta". Copia ese nombre con guiones (ej. "lumiose-city")
 * y añádelo al diccionario con su traducción.
 */
